# The name of the work flow. Badges will use this name
name: 'Publish Snapshot'

on:
  push:
    branches:
      - 'release/*' 

jobs:
  Publish-And-Merge:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2

    - name: 'Tag Package Manifest'
      uses: ArcticFox-Dev/UpmManifestTools@develop
      with:
        dir: ${{ './Package' }}
        action: 'patch'

    - name: 'Publish to UPM'
      uses: actions/setup-node@v1
      with:
        node-version: 10
    
    - name: 'Node Install'
      run: npm install
    
    - name: 'Push to UPM registry'
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        registry: ${{ 'http://upm.randhall.net' }}
        package: ${{ './SignalsGenerator_Package/Assets/SignalsGenerator/package.json' }}

    - name: 'Push Changes'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

    - name: 'Merge to Main'
      uses: devmasx/merge-branch@master
      with:
        type: now
        target_branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Merge to Develop'
      uses: devmasx/merge-branch@master
      with:
        type: now
        target_branch: develop
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Delete Release Branch'
      uses: dawidd6/action-delete-branch@v3
      with:
        branches: ${{ github.ref }}
        github_token: ${{ secrets.GITHUB_TOKEN }}